import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    EN: {
        welcomeAdmin: "Welcome back, Admin!",
        dashboardSubtitle: "Here's what's happening on GigDial today.",
        totalWorkers: "Total Workers",
        totalCustomers: "Total Customers",
        activeBookings: "Active Bookings",
        totalRevenue: "Total Revenue",
        revenueAnalytics: "Revenue Analytics",
        liveActivity: "Live Activity",
        viewFullHistory: "View Full History",
        pending: "pending",
        liveNow: "Live Now",
        newActivity: "New activity detected on the platform requiring attention.",
        workerRegistration: "New worker registration",
        customerRegistration: "New customer registration",
        disputeRaised: "Dispute raised",
        subscriptionPurchased: "New subscription plan purchased",

        // User Roles
        worker: "Worker",
        customer: "Customer",
        admin: "Admin",
        guest: "Guest",

        // Navigation
        findServices: "Find Services",
        findWorkers: "Find Workers",
        joinAsPro: "Join as Pro",
        howItWorks: "How it Works",
        requireWorker: "Require Worker",
        login: "Log In",
        signup: "Sign Up",
        signupFree: "Sign Up Free",
        overview: "Overview",
        jobRequests: "Job Requests",
        myServices: "My Services",
        messages: "Messages",
        myBookings: "My Bookings",
        earnings: "Earnings",
        profile: "Profile",
        settings: "Settings",
        dashboard: "Dashboard",
        browseServices: "Browse Services",
        serviceHistory: "Service History",
        mySubscriptions: "My Subscriptions",
        favorites: "Favorites",
        wallet: "Wallet",
        savedAddresses: "Saved Addresses",
        referEarn: "Refer & Earn",
        loyaltyPoints: "Loyalty Points",
        manageWorkers: "Manage Workers",
        manageCustomers: "Manage Customers",
        bookings: "Bookings",
        disputes: "Disputes",
        analytics: "Analytics",
        services: "Services",
        content: "Content",
        complain: "Complain",
        submitComplain: "Submit Complain",

        // Worker Dashboard
        totalEarnings: "Total Earnings",
        activeLeads: "Active Leads",
        responseRate: "Response Rate",
        rating: "Rating",
        newLeads: "New Leads",
        upcomingJobs: "Upcoming Jobs",
        completed: "Completed",
        payout: "Payout",
        newOpportunities: "New Opportunities",
        availableBalance: "Available Balance",
        requestPayout: "Request Payout",
        viewHistory: "View History",
        bankAccount: "Bank Account",
        verified: "Verified",
        quickProfile: "Quick Profile",
        availability: "Availability",
        addNewSkill: "Add New Skill",
        trainingVideos: "Training Videos",
        achievements: "Achievements",
        topResponder: "Top Responder",
        fiveStarWorker: "5 Star Worker",
        localLeaderboard: "Local Leaderboard",
        accept: "Accept",
        negotiate: "Negotiate",
        decline: "Decline",

        // Customer Dashboard
        newBooking: "New Booking",
        myFavorites: "My Favorites",
        active: "Active",
        support: "Support",
        canceled: "Canceled",
        upcoming: "Upcoming",
        all: "All",
        call: "Call",
        chat: "Chat",
        cancel: "Cancel",
        totalPaid: "Total Paid",
        rateWorker: "Rate Worker",
        rateExperience: "Rate your experience",
        writeReview: "Write a brief review (optional)...",
        submitReview: "Submit Review",
        addMoney: "Add Money",
        history: "History",
        suggestedForYou: "Suggested for You",
        aiPicks: "AI Picks",
        reviewPending: "Review Pending",

        // Landing Page
        searchServices: "Aapko kaunsi service chahiye?",
        heroTitle: "Apne area ke trusted workers instantly hire kare",
        heroPricing: "",
        heroSubtitle: "Plumber, Electrician, Carpenter aur 45+ services – bina middleman",
        heroCTA: "GigDial – kaam turant, bina tension",
        popularServices: "Popular: House Cleaning, AC Repair, Plumbing",
        statsProfessionals: "Verified Workers",
        statsBookings: "Bookings Completed",
        statsRating: "Average Rating",
        statsCities: "Cities Covered",

        // Trust Badges
        noCommission: "No Commission",
        instantBooking: "Instant Booking",
        securePayment: "Secure Payment",

        // Categories
        viewWorkers: "View Workers",

        // How it Works
        step1Title: "Search Best Workers",
        step1Desc: "Choose from thousands of verified professionals in your area.",
        step2Title: "Connect & Book",
        step2Desc: "View profiles, ratings, and chat directly to discuss.",
        step3Title: "Hire & Pay Securely",
        step3Desc: "Get the job done. Release payment only after satisfaction.",
    },
    HI: {
        welcomeAdmin: "वापसी पर स्वागत है, एडमिन!",
        dashboardSubtitle: "गिगडायल पर आज क्या हो रहा है, यहाँ देखें।",
        totalWorkers: "कुल कार्यकर्ता",
        totalCustomers: "कुल ग्राहक",
        activeBookings: "सक्रिय बुकिंग",
        totalRevenue: "कुल राजस्व",
        revenueAnalytics: "राजस्व विश्लेषण",
        liveActivity: "लाइव गतिविधि",
        viewFullHistory: "पूरा इतिहास देखें",
        pending: "लंबित",
        liveNow: "अभी लाइव",
        newActivity: "प्लेटफ़ॉर्म पर नई गतिविधि का पता चला है जिस पर ध्यान देने की आवश्यकता है।",
        workerRegistration: "नई कार्यकर्ता पंजीकरण",
        customerRegistration: "नई ग्राहक पंजीकरण",
        disputeRaised: "विवाद उठाया गया",
        subscriptionPurchased: "नई सदस्यता योजना खरीदी गई",

        worker: "कार्यकर्ता",
        customer: "ग्राहक",
        admin: "एडमिन",
        guest: "मेहमान",
        findServices: "Service खोजें",
        findWorkers: "Worker खोजें",
        joinAsPro: "Worker बनें",
        howItWorks: "यह कैसे काम करता है",
        requireWorker: "कार्यकर्ता की आवश्यकता है",
        login: "लॉग इन करें",
        signup: "साइन अप करें",
        signupFree: "मुफ़्त साइन अप करें",
        overview: "अवलोकन",
        jobRequests: "नौकरी के अनुरोध",
        myServices: "मेरी सेवाएं",
        messages: "संदेश",
        myBookings: "मेरी बुकिंग",
        earnings: "कमाई",
        profile: "प्रोफ़ाइल",
        settings: "सेटिंग्स",
        dashboard: "डैशबोर्ड",
        browseServices: "सेवाएं ब्राउज़ करें",
        serviceHistory: "सेवा इतिहास",
        mySubscriptions: "मेरी सदस्यताएं",
        favorites: "पसंदीदा",
        wallet: "वॉलेट",
        savedAddresses: "सहेजे गए पते",
        referEarn: "रेफर करें और कमाएं",
        loyaltyPoints: "लॉयल्टी पॉइंट्स",
        manageWorkers: "कार्यकर्ताओं का प्रबंधन करें",
        manageCustomers: "ग्राहकों का प्रबंधन करें",
        bookings: "बुकिंग",
        disputes: "विवाद",
        analytics: "एनालिटिक्स",
        services: "सेवाएं",
        content: "सामग्री",
        complain: "शिकायत",
        submitComplain: "शिकायत दर्ज करें",
        totalEarnings: "कुल कमाई",
        activeLeads: "सक्रिय लीड्स",
        responseRate: "प्रतिक्रिया दर",
        rating: "रेटिंग",
        newLeads: "नई लीड्स",
        upcomingJobs: "आगामी नौकरियां",
        completed: "पूर्ण",
        payout: "भुगतान",
        newOpportunities: "नए अवसर",
        availableBalance: "उपलब्ध शेष राशि",
        requestPayout: "भुगतान का अनुरोध करें",
        viewHistory: "इतिहास देखें",
        bankAccount: "बैंक खाता",
        verified: "सत्यापित",
        quickProfile: "त्वरित प्रोफ़ाइल",
        availability: "उपलब्धता",
        addNewSkill: "नया कौशल जोड़ें",
        trainingVideos: "प्रशिक्षण वीडियो",
        achievements: "उपलब्धियां",
        topResponder: "शीर्ष उत्तरदाता",
        fiveStarWorker: "5 स्टार कार्यकर्ता",
        localLeaderboard: "स्थानीय लीडरबोर्ड",
        accept: "स्वीकार करें",
        negotiate: "बातचीत करें",
        decline: "अस्वीकार करें",
        newBooking: "नई बुकिंग",
        myFavorites: "मेरे पसंदीदा",
        active: "सक्रिय",
        support: "सहायता",
        canceled: "रद्द",
        upcoming: "आगामी",
        all: "सभी",
        call: "कॉल करें",
        chat: "चैट करें",
        cancel: "रद्द करें",
        totalPaid: "कुल भुगतान किया गया",
        rateWorker: "कार्यकर्ता को रेट करें",
        rateExperience: "अपने अनुभव को रेट करें",
        writeReview: "एक संक्षिप्त समीक्षा लिखें (वैकल्पिक)...",
        submitReview: "समीक्षा जमा करें",
        addMoney: "पैसे जोड़ें",
        history: "इतिहास",
        suggestedForYou: "आपके लिए सुझाव",
        aiPicks: "एआई पिक्स",
        reviewPending: "समीक्षा लंबित",
        searchServices: "आपको कौन सी सर्विस चाहिए?",
        heroTitle: "अपने एरिया के ट्रस्टेड वर्कर्स को तुरंत हायर करें",
        heroPricing: "",
        heroSubtitle: "प्लंबर, इलेक्ट्रीशियन, बढ़ई और 45+ सेवाएं - बिना बिचौलिए के",
        heroCTA: "गिगडायल - काम तुरंत, बिना टेंशन",
        popularServices: "लोकप्रिय: घर की सफाई, एसी मरम्मत, नलसाजी",
        statsProfessionals: "सत्यापित कार्यकर्ता",
        statsBookings: "बुकिंग पूरी हुई",
        statsRating: "औसत रेटिंग",
        statsCities: "शहर कवर किए गए",

        // Trust Badges
        noCommission: "कोई कमीशन नहीं",
        instantBooking: "तत्काल बुकिंग",
        securePayment: "सुरक्षित भुगतान",

        // Categories
        viewWorkers: "कार्यकर्ता देखें",

        // How it Works
        step1Title: "सर्वश्रेष्ठ कार्यकर्ता खोजें",
        step1Desc: "अपने क्षेत्र में हजारों सत्यापित पेशेवरों में से चुनें।",
        step2Title: "कनेक्ट और बुक करें",
        step2Desc: "प्रोफाइल, रेटिंग देखें और सीधे चैट करें।",
        step3Title: "सुरक्षित रूप से हायर करें",
        step3Desc: "काम पूरा करें। संतुष्टि के बाद ही भुगतान जारी करें।",
    },
    GU: {
        welcomeAdmin: "સ્વાગત છે, એડમિન!",
        dashboardSubtitle: "ગીગડાયલ પર આજે શું થઈ રહ્યું છે તે અહીં છે.",
        totalWorkers: "કુલ કામદારો",
        totalCustomers: "કુલ ગ્રાહકો",
        activeBookings: "સક્રિય બુકિંગ",
        totalRevenue: "કુલ આવક",
        revenueAnalytics: "આવક વિશ્લેષણ",
        liveActivity: "જીવંત પ્રવૃત્તિ",
        viewFullHistory: "સંપૂર્ણ ઇતિહાસ જુઓ",
        pending: "બાકી",
        liveNow: "હવે લાઈવ",
        newActivity: "પ્લેટફોર્મ પર નવી પ્રવૃત્તિ મળી છે જેના પર ધ્યાન આપવાની જરૂર છે.",
        workerRegistration: "નવી કામદાર નોંધણી",
        customerRegistration: "નવી ગ્રાહક નોંધણી",
        disputeRaised: "વિવાદ ઉભો થયો",
        subscriptionPurchased: "નવી સબ્સ્ક્રિપ્શન યોજના ખરીદી",

        worker: "કામદાર",
        customer: "ગ્રાહક",
        admin: "એડમિન",
        guest: "મહેમાન",
        findServices: "સેવાઓ શોધો",
        findWorkers: "કામદારો શોધો",
        joinAsPro: "પ્રો તરીકે જોડાઓ",
        howItWorks: "તે કેવી રીતે કામ કરે છે",
        requireWorker: "કામદારની જરૂર છે",
        login: "લોગ ઇન કરો",
        signup: "સાઇન અપ કરો",
        signupFree: "મફત સાઇન અપ કરો",
        overview: "ઝાંખી",
        jobRequests: "નોકરીની વિનંતીઓ",
        myServices: "મારી સેવાઓ",
        messages: "સંદેશાઓ",
        myBookings: "મારી બુકિંગ્સ",
        earnings: "કમાણી",
        profile: "પ્રોફાઇલ",
        settings: "સેટિંગ્સ",
        dashboard: "ડેશબોર્ડ",
        browseServices: "સેવાઓ બ્રાઉઝ કરો",
        serviceHistory: "સેવા ઇતિહાસ",
        mySubscriptions: "મારા સબ્સ્ક્રિપ્શન્સ",
        favorites: "મનપસંદ",
        wallet: "વોલેટ",
        savedAddresses: "સાચવેલા સરનામાં",
        referEarn: "રેફર કરો અને કમાઓ",
        loyaltyPoints: "લોયલ્ટી પોઈન્ટ્સ",
        manageWorkers: "કામદારોનું સંચાલન કરો",
        manageCustomers: "ગ્રાહકોનું સંચાલન કરો",
        bookings: "બુકિંગ્સ",
        disputes: "વિવાદો",
        analytics: "એનાલિટિક્સ",
        services: "સેવાઓ",
        content: "સામગ્રી",
        complain: "ફરિયાદ",
        submitComplain: "ફરિયાદ સબમિટ કરો",
        totalEarnings: "કુલ કમાણી",
        activeLeads: "સક્રિય લીડ્સ",
        responseRate: "પ્રતિસાદ દર",
        rating: "રેટિંગ",
        newLeads: "નવી લીડ્સ",
        upcomingJobs: "આગામી નોકરીઓ",
        completed: "પૂર્ણ",
        payout: "ચુકવણી",
        newOpportunities: "નવી તકો",
        availableBalance: "ઉપલબ્ધ બેલેન્સ",
        requestPayout: "ચુકવણીની વિનંતી કરો",
        viewHistory: "ઇતિહાસ જુઓ",
        bankAccount: "બેંક એકાઉન્ટ",
        verified: "ચકાસાયેલ",
        quickProfile: "ઝડપી પ્રોફાઇલ",
        availability: "ઉપલબ્ધતા",
        addNewSkill: "નવું કૌશલ્ય ઉમેરો",
        trainingVideos: "તાલીમ વિડિઓઝ",
        achievements: "સિદ્ધિઓ",
        topResponder: "ટોચના પ્રતિસાદકર્તા",
        fiveStarWorker: "5 સ્ટાર કામદાર",
        localLeaderboard: "સ્થાનિક લીડરબોર્ડ",
        accept: "સ્વીકારો",
        negotiate: "વાટાઘાટો",
        decline: "નકારો",
        newBooking: "નવી બુકિંગ",
        myFavorites: "મારા મનપસંદ",
        active: "સક્રિય",
        support: "સહાય",
        canceled: "રદ",
        upcoming: "આગામી",
        all: "બધા",
        call: "કોલ કરો",
        chat: "ચેટ કરો",
        cancel: "રદ કરો",
        totalPaid: "કુલ ચૂકવેલ",
        rateWorker: "કામદારને રેટ કરો",
        rateExperience: "તમારા અનુભવને રેટ કરો",
        writeReview: "એક ટૂંકી સમીક્ષા લખો (વૈકલ્પિક)...",
        submitReview: "સમીક્ષા સબમિટ કરો",
        addMoney: "પૈસા ઉમેરો",
        history: "ઇતિહાસ",
        suggestedForYou: "તમારા માટે સૂચવેલ",
        aiPicks: "એઆઈ પિક્સ",
        reviewPending: "સમીક્ષા બાકી",
        searchServices: "સેવાઓ શોધો...",
        heroTitle: "એક કામ, એક સમય, એક પૈસા",
        heroPricing: "માત્ર ₹500/મહિનો",
        heroSubtitle: "દરેક કામદારનું સ્વપ્ન, દરેક ગ્રાહકનો હક!",
        getStarted: "શરૂ કરો",
        popularServices: "લોકપ્રિય: ઘરની સફાઈ, એસી રિપેર, પ્લમ્બિંગ",
        statsProfessionals: "ચકાસાયેલ કામદારો",
        statsBookings: "બુકિંગ પૂર્ણ",
        statsRating: "સરેરાશ રેટિંગ",
        statsCities: "શહેરો આવરી લેવાયેલ",

        // Trust Badges
        noCommission: "કોઈ કમિશન નથી",
        instantBooking: "ત્વરિત બુકિંગ",
        securePayment: "સુરક્ષિત ચુકવણી",

        // Categories
        viewWorkers: "કામદારો જુઓ",

        // How it Works
        step1Title: "શ્રેષ્ઠ કામદારો શોધો",
        step1Desc: "તમારા વિસ્તારમાં હજારો ચકાસાયેલ વ્યાવસાયિકોમાંથી પસંદ કરો.",
        step2Title: "કનેક્ટ કરો અને બુક કરો",
        step2Desc: "પ્રોફાઇલ, રેટિંગ્સ જુઓ અને સીધી ચેટ કરો.",
        step3Title: "હાયર કરો અને સુરક્ષિત રીતે ચૂકવો",
        step3Desc: "કામ પૂર્ણ કરો. સંતોષ પછી જ ચુકવણી કરો.",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('EN');

    const t = (key) => {
        return translations[language][key] || translations['EN'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
